import {Box, HStack, Image, Stack, Text} from "@chakra-ui/react";
import Head from "next/head";

import ProductList from "../components/ProductList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Aerolab Challenge</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Box>
        <Stack
          alignItems={"center"}
          direction={"row"}
          justifyContent={"space-between"}
          px={8}
          py={2}
        >
          <Image alt="Aerolab Icon" src={"/aerolab-logo.svg"} width={"30px"} />
          <Stack alignItems={"center"} color={"blackAlpha.700"} direction={"row"}>
            <Text>John Kite</Text>
            <HStack alignItems={"flex-end"} bg={"blackAlpha.200"} borderRadius={15} px={2} py={1}>
              {" "}
              <Text>6000</Text>
              <Image alt="Coin" src={"/coin.svg"} width={5} />
            </HStack>
          </Stack>
        </Stack>
      </Box>
      <Box h={350}>
        <Image
          align={{base: "-500px", sm: "center"}}
          h={"100%"}
          objectFit={"cover"}
          src="/header-x1.png"
          width={"100%"}
        />
        <Text
          color={"white"}
          fontSize={{base: "3xl", lg: "5xl"}}
          fontWeight={700}
          position={"absolute"}
          px={{base: 10, lg: 40}}
          top={{base: "320px", lg: "270px"}}
        >
          Electronics
        </Text>
      </Box>
      <Box bgColor={"rgb(250,250,250)"} px={{base: 5, lg: 40}} py={10}>
        <ProductList />
      </Box>
    </div>
  );
}
