import {Box, Image, Text} from "@chakra-ui/react";
import Head from "next/head";

import Nav from "../components/Nav";
import ProductList from "../components/ProductList";
import {UserProvider} from "../context/UserContext";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Aerolab Challenge | Octavio Rossi</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/aerolab-logo.svg" rel="icon" />
      </Head>
      <UserProvider>
        <Nav />
        <Box h={350}>
          <Image
            align={{base: "-500px", sm: "center"}}
            h={"100%"}
            objectFit={"cover"}
            src="/header-x1.png"
            width={"100%"}
          />
          <Text
            color={"white"}
            fontSize={{base: "3xl", lg: "5xl"}}
            fontWeight={700}
            position={"absolute"}
            px={{base: 5, lg: 40}}
            top={{base: "320px", lg: "270px"}}
          >
            Electronics
          </Text>
        </Box>
        <Box bgColor={"rgb(250,250,250)"} px={{base: 5, xl: 40}} py={10}>
          <ProductList />
        </Box>
      </UserProvider>
    </div>
  );
}
